# Name: Jingjing
# Email: 
# ID: 

CC = gcc
CFLAGS = -g -Wall -Wextra

default: lab1a.c
	$(CC) $(CFLAGS) lab1a.c -o lab1a

clean:
	rm -f lab1a *.o *.tar.gz

dist:
	tar -czf lab1a-304567417.tar.gz lab1a.c Makefile README
